name: UFC Prediction Pipeline

on:
  #schedule:
    #- cron: "0 7 * * 2"  # Ejecutar a las 7 AM UTC cada martes
  workflow_dispatch:  # Permite ejecutar manualmente el pipeline desde GitHub Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run UFC pipeline
      run: |
        python UFC_Pipeline.py

    - name: Scrape fight stats
      run: |
        python -c "from ufc_predictor.scraping import scrape_fight_stats; scrape_fight_stats()"

    - name: Generate fight statistics
      run: |
        python -m ufc_predictor.fight_stats

    - name: Configurar git para commit
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"

    - name: Forzar commit de modelos y datos
      run: |
        git add data/ 
        git commit -m "Actualización automática de modelos y datos" --allow-empty

    - name: Forzar push al repositorio
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git pull --rebase origin main || echo "No hay cambios remotos."
        git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
